#!/usr/bin/env python3
"""Regenerate ``docs/kiwimatecoder.1`` from the Typer/Click command tree.

The man page is generated from the same command objects the CLI uses, so
options and help text stay in sync with ``kiwimatecoder --help``. Run it after
adding or changing a command or option:

    python scripts/generate_man.py

``--check`` compares the committed file with what would be generated and exits
non-zero when it is stale (handy in CI); it never writes anything.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import click
import typer.main

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from kiwimatecoder import __version__  # noqa: E402
from kiwimatecoder.main import app  # noqa: E402

MAN_PATH = ROOT / "docs" / "kiwimatecoder.1"

_ENVIRONMENT = (
    ("OPENROUTER_API_KEY", "OpenRouter API key (default provider)."),
    ("OPENAI_API_KEY", "OpenAI API key."),
    ("ANTHROPIC_API_KEY", "Anthropic API key."),
    ("DEEPSEEK_API_KEY", "DeepSeek API key."),
    ("KIWIMATECODER_PROJECT_CONFIG", "Path to a project config overlay."),
    ("KIWIMATECODER_DEBUG", "Force the debug telemetry level for one run."),
    ("NO_COLOR", "Disable ANSI color output when set."),
)


def _troff(text: object) -> str:
    """Collapse whitespace and make a string safe for a troff fill line."""
    cleaned = " ".join(str(text or "").split())
    cleaned = cleaned.replace("\\", r"\\")
    if cleaned.startswith((".", "'")):
        cleaned = r"\&" + cleaned
    return cleaned


def _bold(text: str) -> str:
    return r"\fB" + text.replace("-", r"\-") + r"\fP"


def _italic(text: str) -> str:
    return r"\fI" + text.replace("-", r"\-") + r"\fP"


def _metavar(param: click.Parameter) -> str:
    """A short uppercase placeholder for an option or a positional argument."""
    type_name = getattr(param.type, "name", "text") or "text"
    return type_name.upper().replace("_", " ")


def _option_label(param: click.Parameter) -> str:
    names = ", ".join(_bold(opt) for opt in param.opts)
    if isinstance(param.type, click.Choice):
        choices = "|".join(str(choice) for choice in param.type.choices)
        label = f"{names} {_italic(choices)}"
    elif getattr(param, "is_flag", False) or getattr(param, "count", False):
        label = names
    else:
        label = f"{names} {_italic(_metavar(param))}"
    if param.required:
        label += " (required)"
    return label


def _option_help(param: click.Parameter) -> str:
    help_text = _troff(param.help or "No description.")
    default = param.default
    if default is not None and default is not False and default != () and str(default) not in help_text:
        help_text += f" Default: {_troff(default)}."
    return help_text


def _argument_usage(param: click.Argument) -> str:
    name = str(param.name).upper()
    if param.nargs == -1:
        return f"{name}..."
    return name if param.required else f"[{name}]"


def _command_usage(path: str, command: click.Command) -> str:
    parts = ["kiwimatecoder"]
    if path:
        parts.append(path)
    parts.append("[OPTIONS]")
    for param in command.params:
        if not isinstance(param, click.Parameter):
            continue
        if isinstance(param, click.Argument):
            parts.append(_argument_usage(param))
    return " ".join(parts)


def _render_params(command: click.Command) -> list[str]:
    """Render every option and positional argument as ``.TP`` blocks."""
    lines: list[str] = []
    for param in command.params:
        if isinstance(param, click.Option):
            lines.append(".TP")
            lines.append(_option_label(param))
            lines.append(_option_help(param))
        elif isinstance(param, click.Argument):
            lines.append(".TP")
            lines.append(_bold(_argument_usage(param)))
            lines.append("Positional argument.")
    return lines


def _walk(command: click.Command, prefix: str) -> list[tuple[str, click.Command]]:
    found: list[tuple[str, click.Command]] = []
    if not isinstance(command, click.Group):
        return found
    ctx = click.Context(command)
    for name in command.list_commands(ctx):
        sub = command.get_command(ctx, name)
        if sub is None or sub.hidden:
            continue
        path = f"{prefix} {name}".strip()
        found.append((path, sub))
        found.extend(_walk(sub, path))
    return found


def render_man() -> str:
    """Return the full man page as troff text (deterministic, no timestamps)."""
    root = typer.main.get_command(app)
    lines: list[str] = [
        r'.\" Generated by scripts/generate_man.py -- do not edit by hand.',
        f'.TH KIWIMATECODER 1 "" "kiwimatecoder {__version__}" "User Commands"',
        ".SH NAME",
        "kiwimatecoder \\- agentic AI coding assistant CLI",
        ".SH SYNOPSIS",
        ".B kiwimatecoder",
        r".RI [ options ]",
        r".RI [ command ]",
        r".RI [ command-options ]",
        ".SH DESCRIPTION",
        _troff(
            "KiwiMateCoder is a terminal coding agent: it chats about a workspace, "
            "reads and edits files, runs shell commands, and can operate headlessly "
            "in scripts and CI. Run it with no arguments for an interactive session, "
            "or use a subcommand for one-shot and management tasks."
        ),
        ".SH OPTIONS",
    ]
    lines.extend(_render_params(root))
    for flag, help_text in (
        (
            "--install-completion [SHELL]",
            "Install shell completion for the current shell and exit.",
        ),
        (
            "--show-completion [SHELL]",
            "Print the shell completion script and exit.",
        ),
        ("--help", "Show this message and exit."),
    ):
        lines.append(".TP")
        lines.append(_bold(flag.split(" [")[0]) + (" [SHELL]" if "[" in flag else ""))
        lines.append(_troff(help_text))

    lines.append(".SH COMMANDS")
    lines.append(
        _troff(
            "Commands may be nested (for example 'config key set'). Each command "
            "accepts --help."
        )
    )
    for path, command in _walk(root, ""):
        lines.append(f".SS {_bold(path)}")
        summary = command.get_short_help_str() or "No description."
        lines.append(_troff(summary))
        lines.append(".PP")
        lines.append(".nf")
        lines.append(_command_usage(path, command))
        lines.append(".fi")
        params = _render_params(command)
        if params:
            lines.extend(params)
        lines.append(".TP")
        lines.append(_bold("--help"))
        lines.append("Show this command's help and exit.")

    lines.extend(
        [
            ".SH FILES",
            ".TP",
            _bold("~/.kiwimatecoder/config.json"),
            "Global configuration (keys, provider, model, mode, settings).",
            ".TP",
            _bold("~/.kiwimatecoder/sessions/"),
            "Saved and autosaved sessions.",
            ".TP",
            _bold(".kiwimatecoder.json"),
            "Optional project-level config overlay in the workspace root.",
            ".SH ENVIRONMENT",
        ]
    )
    for name, help_text in _ENVIRONMENT:
        lines.append(".TP")
        lines.append(_bold(name))
        lines.append(_troff(help_text))

    lines.extend(
        [
            ".SH EXIT STATUS",
            ".TP",
            _bold("0"),
            "Success.",
            ".TP",
            _bold("1"),
            "Runtime failure (for example a missing API key or provider error).",
            ".TP",
            _bold("2"),
            "Invalid usage, or an interactive session attempted without a TTY.",
            ".SH SEE ALSO",
            "kiwimatecoder --help, docs/ci.md, README.md",
        ]
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the committed man page is stale.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=MAN_PATH,
        help=f"Target file (default: {MAN_PATH}).",
    )
    args = parser.parse_args(argv)
    rendered = render_man()
    target = args.output
    if args.check:
        try:
            current = target.read_text(encoding="utf-8")
        except OSError:
            current = None
        if current == rendered:
            print(f"{target} is up to date.")
            return 0
        sys.stderr.write(
            f"{target} is out of date; run: python scripts/generate_man.py\n"
        )
        return 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())