# Homebrew formula template for KiwiMateCoder.
#
# This is a template, not a published tap formula: it pins a tag and needs its
# `resource` blocks generated for each release. It is intentionally kept in the
# repository (rather than a tap) until the project publishes tagged releases.
#
# How to bump the version:
#   1. Tag the release on GitHub (for example `v0.2.0`) and copy the tag's full
#      commit SHA.
#   2. Update `tag:` and `revision:` below (and `version:` if it no longer
#      matches the tag).
#   3. Regenerate the vendored pip dependencies with:
#        brew update-python-resources --print-only packaging/homebrew/kiwimatecoder.rb
#      and paste the printed `resource` blocks below `depends_on`.
#   4. Verify with:
#        brew install --build-from-source ./packaging/homebrew/kiwimatecoder.rb
#        brew test kiwimatecoder
class Kiwimatecoder < Formula
  include Language::Python::Virtualenv

  desc "Agentic AI coding assistant CLI"
  homepage "https://github.com/Kyle8933/kiwimatecoder"
  url "https://github.com/Kyle8933/kiwimatecoder.git",
      tag:      "v0.1.0", # TODO: bump to the release tag
      revision: "0000000000000000000000000000000000000000" # TODO: tag commit SHA
  version "0.1.0"
  license "MIT"

  depends_on "python@3.12"

  # Generated by `brew update-python-resources` (see step 3 above); one
  # resource per runtime dependency, for example:
  #
  # resource "typer" do
  #   url "https://files.pythonhosted.org/.../typer-0.12.3.tar.gz"
  #   sha256 "..."
  # end
  # resource "rich" do ... end
  # resource "httpx" do ... end
  # resource "prompt_toolkit" do ... end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "kiwimatecoder", shell_output("#{bin}/kiwimatecoder --version")
  end
end
